development:
  base_url: 'https://quizachu-backend-h67ch72r3q-ew.a.run.app/'
 
test:
  base_url: 'https://quizachu-backend-h67ch72r3q-ew.a.run.app/'
 
production:
  base_url: 'https://quizachu-backend-h67ch72r3q-ew.a.run.app/'